create table public.auditores_cadastrados (
  id bigint generated by default as identity primary key,
  origem text not null,
  origem_id bigint not null,
  nome text not null,
  cargo text not null,
  setor text not null,
  ativo boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint auditores_cadastrados_origem_check
    check (origem in ('lideranca', 'operacional')),
  constraint auditores_cadastrados_nome_not_blank check (btrim(nome) <> ''),
  constraint auditores_cadastrados_cargo_not_blank check (btrim(cargo) <> ''),
  constraint auditores_cadastrados_setor_not_blank check (btrim(setor) <> '')
);

create unique index auditores_cadastrados_origem_ativo_uidx
  on public.auditores_cadastrados (origem, origem_id)
  where ativo;

create unique index auditores_cadastrados_nome_ativo_uidx
  on public.auditores_cadastrados (lower(btrim(nome)))
  where ativo;

create index auditores_cadastrados_setor_nome_ativo_idx
  on public.auditores_cadastrados (setor, nome)
  where ativo;

alter table public.auditores_cadastrados enable row level security;

create policy "Auditores ativos são públicos para seleção"
  on public.auditores_cadastrados
  for select
  to anon, authenticated
  using (ativo);

revoke all on table public.auditores_cadastrados from anon, authenticated;
grant select on table public.auditores_cadastrados to anon, authenticated;
grant all on table public.auditores_cadastrados to service_role;

create view public.auditores_publicos
with (security_invoker = true)
as
select id, origem, origem_id, nome, cargo, setor, created_at, updated_at
from public.auditores_cadastrados
where ativo;

revoke all on table public.auditores_publicos from public;
grant select on table public.auditores_publicos to anon, authenticated, service_role;

create or replace function public.save_auditor_cadastrado(
  p_password text,
  p_id bigint,
  p_origem text,
  p_origem_id bigint
)
returns bigint
language plpgsql
security definer
set search_path = ''
as $$
declare
  v_id bigint;
  v_origem text := lower(btrim(coalesce(p_origem, '')));
  v_nome text;
  v_cargo text;
  v_setor text;
begin
  if not public.admin_password_ok(p_password) then
    raise exception 'Senha administrativa inválida';
  end if;

  if v_origem not in ('lideranca', 'operacional') or p_origem_id is null then
    raise exception 'Selecione um colaborador cadastrado';
  end if;

  if v_origem = 'lideranca' then
    select lider.nome, lider.cargo, lider.setor
    into v_nome, v_cargo, v_setor
    from public.liderancas lider
    where lider.id = p_origem_id
      and lider.ativo;
  else
    select colaborador.subordinado, colaborador.cargo, colaborador.setor
    into v_nome, v_cargo, v_setor
    from public.subordinacoes colaborador
    where colaborador.id = p_origem_id
      and colaborador.ativo;
  end if;

  if v_nome is null then
    raise exception 'O auditor precisa ser uma liderança ou um colaborador operacional ativo';
  end if;

  if exists (
    select 1
    from public.auditores_cadastrados auditor
    where auditor.ativo
      and lower(btrim(auditor.nome)) = lower(btrim(v_nome))
      and (p_id is null or auditor.id <> p_id)
  ) then
    raise exception 'Este colaborador já está cadastrado como auditor';
  end if;

  if p_id is null then
    insert into public.auditores_cadastrados (origem, origem_id, nome, cargo, setor)
    values (v_origem, p_origem_id, v_nome, v_cargo, v_setor)
    returning id into v_id;
  else
    update public.auditores_cadastrados
    set origem = v_origem,
        origem_id = p_origem_id,
        nome = v_nome,
        cargo = v_cargo,
        setor = v_setor,
        ativo = true,
        updated_at = now()
    where id = p_id
    returning id into v_id;

    if v_id is null then
      raise exception 'Cadastro de auditor não encontrado';
    end if;
  end if;

  return v_id;
end;
$$;

create or replace function public.delete_auditor_cadastrado(
  p_password text,
  p_id bigint
)
returns boolean
language plpgsql
security definer
set search_path = ''
as $$
declare
  v_afetados integer;
begin
  if not public.admin_password_ok(p_password) then
    raise exception 'Senha administrativa inválida';
  end if;

  update public.auditores_cadastrados
  set ativo = false,
      updated_at = now()
  where id = p_id
    and ativo;

  get diagnostics v_afetados = row_count;
  return v_afetados > 0;
end;
$$;

create table public.sugestoes_melhoria (
  id bigint generated by default as identity primary key,
  titulo text not null,
  descricao text not null,
  status text not null default 'Registrada',
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint sugestoes_melhoria_titulo_not_blank check (btrim(titulo) <> ''),
  constraint sugestoes_melhoria_descricao_not_blank check (btrim(descricao) <> ''),
  constraint sugestoes_melhoria_status_check check (
    status in ('Registrada', 'Em análise', 'Aprovada', 'Em implementação', 'Concluída', 'Não aprovada')
  )
);

create index sugestoes_melhoria_status_updated_idx
  on public.sugestoes_melhoria (status, updated_at desc);

create table public.sugestoes_melhoria_autores (
  sugestao_id bigint not null references public.sugestoes_melhoria(id) on delete cascade,
  origem text not null,
  origem_id bigint not null,
  nome text not null,
  cargo text not null,
  setor text not null,
  created_at timestamptz not null default now(),
  constraint sugestoes_melhoria_autores_pkey primary key (sugestao_id, origem, origem_id),
  constraint sugestoes_melhoria_autores_origem_check
    check (origem in ('lideranca', 'operacional')),
  constraint sugestoes_melhoria_autores_nome_not_blank check (btrim(nome) <> '')
);

create unique index sugestoes_melhoria_autores_nome_uidx
  on public.sugestoes_melhoria_autores (sugestao_id, lower(btrim(nome)));

create index sugestoes_melhoria_autores_pessoa_idx
  on public.sugestoes_melhoria_autores (origem, origem_id, sugestao_id);

create table public.sugestoes_melhoria_auditorias (
  sugestao_id bigint not null references public.sugestoes_melhoria(id) on delete cascade,
  auditoria_id bigint not null references public.auditorias(audit_id) on delete cascade,
  created_at timestamptz not null default now(),
  constraint sugestoes_melhoria_auditorias_pkey primary key (sugestao_id, auditoria_id)
);

create index sugestoes_melhoria_auditorias_auditoria_idx
  on public.sugestoes_melhoria_auditorias (auditoria_id, sugestao_id);

create table public.sugestoes_melhoria_status_historico (
  id bigint generated by default as identity primary key,
  sugestao_id bigint not null references public.sugestoes_melhoria(id) on delete cascade,
  status text not null,
  observacao text,
  created_at timestamptz not null default now(),
  constraint sugestoes_melhoria_status_historico_status_check check (
    status in ('Registrada', 'Em análise', 'Aprovada', 'Em implementação', 'Concluída', 'Não aprovada')
  ),
  constraint sugestoes_melhoria_status_historico_observacao_check
    check (observacao is null or btrim(observacao) <> '')
);

create index sugestoes_melhoria_status_historico_sugestao_idx
  on public.sugestoes_melhoria_status_historico (sugestao_id, created_at desc);

alter table public.sugestoes_melhoria enable row level security;
alter table public.sugestoes_melhoria_autores enable row level security;
alter table public.sugestoes_melhoria_auditorias enable row level security;
alter table public.sugestoes_melhoria_status_historico enable row level security;

create policy "Sugestões são públicas para acompanhamento"
  on public.sugestoes_melhoria
  for select
  to anon, authenticated
  using (true);

create policy "Autores das sugestões são públicos para acompanhamento"
  on public.sugestoes_melhoria_autores
  for select
  to anon, authenticated
  using (true);

create policy "Auditorias de origem são públicas para acompanhamento"
  on public.sugestoes_melhoria_auditorias
  for select
  to anon, authenticated
  using (true);

create policy "Histórico das sugestões é público para acompanhamento"
  on public.sugestoes_melhoria_status_historico
  for select
  to anon, authenticated
  using (true);

revoke all on table public.sugestoes_melhoria from anon, authenticated;
revoke all on table public.sugestoes_melhoria_autores from anon, authenticated;
revoke all on table public.sugestoes_melhoria_auditorias from anon, authenticated;
revoke all on table public.sugestoes_melhoria_status_historico from anon, authenticated;
grant select on table public.sugestoes_melhoria to anon, authenticated;
grant select on table public.sugestoes_melhoria_autores to anon, authenticated;
grant select on table public.sugestoes_melhoria_auditorias to anon, authenticated;
grant select on table public.sugestoes_melhoria_status_historico to anon, authenticated;
grant all on table public.sugestoes_melhoria to service_role;
grant all on table public.sugestoes_melhoria_autores to service_role;
grant all on table public.sugestoes_melhoria_auditorias to service_role;
grant all on table public.sugestoes_melhoria_status_historico to service_role;

create view public.sugestoes_melhoria_publicas
with (security_invoker = true)
as
select
  sugestao.id,
  sugestao.titulo,
  sugestao.descricao,
  sugestao.status,
  sugestao.created_at,
  sugestao.updated_at,
  coalesce(autores.itens, '[]'::jsonb) as autores,
  coalesce(auditorias.ids, array[]::bigint[]) as auditoria_ids,
  coalesce(auditorias.itens, '[]'::jsonb) as auditorias,
  coalesce(historico.itens, '[]'::jsonb) as historico
from public.sugestoes_melhoria sugestao
left join lateral (
  select jsonb_agg(
    jsonb_build_object(
      'origem', autor.origem,
      'origemId', autor.origem_id,
      'nome', autor.nome,
      'cargo', autor.cargo,
      'setor', autor.setor
    )
    order by autor.nome
  ) as itens
  from public.sugestoes_melhoria_autores autor
  where autor.sugestao_id = sugestao.id
) autores on true
left join lateral (
  select
    array_agg(vinculo.auditoria_id order by auditoria.audit_date desc, vinculo.auditoria_id desc) as ids,
    jsonb_agg(
      jsonb_build_object(
        'id', auditoria.audit_id,
        'type', auditoria.type,
        'team', auditoria.team,
        'date', auditoria.audit_date,
        'score', auditoria.score,
        'supervisorName', auditoria.supervisor_name,
        'auditedRole', auditoria.audited_role
      )
      order by auditoria.audit_date desc, vinculo.auditoria_id desc
    ) as itens
  from public.sugestoes_melhoria_auditorias vinculo
  join public.auditoria_resultados auditoria
    on auditoria.audit_id = vinculo.auditoria_id
  where vinculo.sugestao_id = sugestao.id
) auditorias on true
left join lateral (
  select jsonb_agg(
    jsonb_build_object(
      'status', evento.status,
      'observacao', evento.observacao,
      'data', evento.created_at
    )
    order by evento.created_at desc, evento.id desc
  ) as itens
  from public.sugestoes_melhoria_status_historico evento
  where evento.sugestao_id = sugestao.id
) historico on true;

revoke all on table public.sugestoes_melhoria_publicas from public;
grant select on table public.sugestoes_melhoria_publicas to anon, authenticated, service_role;

create or replace function public.save_sugestao_melhoria(
  p_password text,
  p_id bigint,
  p_titulo text,
  p_descricao text,
  p_autores text[],
  p_auditoria_ids bigint[],
  p_status text,
  p_observacao_status text
)
returns bigint
language plpgsql
security definer
set search_path = ''
as $$
declare
  v_id bigint;
  v_titulo text := btrim(coalesce(p_titulo, ''));
  v_descricao text := btrim(coalesce(p_descricao, ''));
  v_status text := coalesce(nullif(btrim(p_status), ''), 'Registrada');
  v_observacao text := nullif(btrim(coalesce(p_observacao_status, '')), '');
  v_status_anterior text;
  v_auditoria_ids bigint[];
begin
  if not public.admin_password_ok(p_password) then
    raise exception 'Senha administrativa inválida';
  end if;

  if v_titulo = '' or v_descricao = '' then
    raise exception 'Título e descrição da sugestão são obrigatórios';
  end if;

  if v_status not in ('Registrada', 'Em análise', 'Aprovada', 'Em implementação', 'Concluída', 'Não aprovada') then
    raise exception 'Status da sugestão inválido';
  end if;

  if coalesce(cardinality(p_autores), 0) = 0 then
    raise exception 'Selecione pelo menos um colaborador como autor da ideia';
  end if;

  if exists (
    select 1
    from unnest(p_autores) selecionado(token)
    where selecionado.token !~ '^(lideranca|operacional):[0-9]+$'
  ) then
    raise exception 'Existe um autor inválido na seleção';
  end if;

  if exists (
    select 1
    from unnest(p_autores) selecionado(token)
    where case split_part(selecionado.token, ':', 1)
      when 'lideranca' then not exists (
        select 1
        from public.liderancas lider
        where lider.id = split_part(selecionado.token, ':', 2)::bigint
          and lider.ativo
      )
      when 'operacional' then not exists (
        select 1
        from public.subordinacoes colaborador
        where colaborador.id = split_part(selecionado.token, ':', 2)::bigint
          and colaborador.ativo
      )
      else true
    end
  ) then
    raise exception 'Todos os autores precisam permanecer cadastrados e ativos';
  end if;

  select coalesce(array_agg(distinct id order by id), array[]::bigint[])
  into v_auditoria_ids
  from unnest(coalesce(p_auditoria_ids, array[]::bigint[])) selecionada(id)
  where id is not null;

  if exists (
    select 1
    from unnest(v_auditoria_ids) selecionada(id)
    left join public.auditorias auditoria on auditoria.audit_id = selecionada.id
    where auditoria.audit_id is null
  ) then
    raise exception 'Uma das auditorias de origem não foi encontrada';
  end if;

  if p_id is null then
    insert into public.sugestoes_melhoria (titulo, descricao, status)
    values (v_titulo, v_descricao, v_status)
    returning id into v_id;
  else
    select status
    into v_status_anterior
    from public.sugestoes_melhoria
    where id = p_id;

    if v_status_anterior is null then
      raise exception 'Sugestão de melhoria não encontrada';
    end if;

    update public.sugestoes_melhoria
    set titulo = v_titulo,
        descricao = v_descricao,
        status = v_status,
        updated_at = now()
    where id = p_id
    returning id into v_id;
  end if;

  delete from public.sugestoes_melhoria_autores where sugestao_id = v_id;

  insert into public.sugestoes_melhoria_autores (
    sugestao_id, origem, origem_id, nome, cargo, setor
  )
  select distinct on (lower(btrim(pessoa.nome)))
    v_id,
    pessoa.origem,
    pessoa.origem_id,
    pessoa.nome,
    pessoa.cargo,
    pessoa.setor
  from (
    select
      'lideranca'::text as origem,
      lider.id as origem_id,
      lider.nome,
      lider.cargo,
      lider.setor
    from unnest(p_autores) selecionado(token)
    join public.liderancas lider
      on split_part(selecionado.token, ':', 1) = 'lideranca'
     and lider.id = split_part(selecionado.token, ':', 2)::bigint
     and lider.ativo
    union all
    select
      'operacional'::text as origem,
      colaborador.id as origem_id,
      colaborador.subordinado as nome,
      colaborador.cargo,
      colaborador.setor
    from unnest(p_autores) selecionado(token)
    join public.subordinacoes colaborador
      on split_part(selecionado.token, ':', 1) = 'operacional'
     and colaborador.id = split_part(selecionado.token, ':', 2)::bigint
     and colaborador.ativo
  ) pessoa
  order by lower(btrim(pessoa.nome)), pessoa.origem, pessoa.origem_id;

  if not exists (
    select 1
    from public.sugestoes_melhoria_autores autor
    where autor.sugestao_id = v_id
  ) then
    raise exception 'Selecione pelo menos um colaborador como autor da ideia';
  end if;

  delete from public.sugestoes_melhoria_auditorias where sugestao_id = v_id;

  insert into public.sugestoes_melhoria_auditorias (sugestao_id, auditoria_id)
  select v_id, selecionada.id
  from unnest(v_auditoria_ids) selecionada(id);

  if p_id is null or v_status_anterior is distinct from v_status or v_observacao is not null then
    insert into public.sugestoes_melhoria_status_historico (sugestao_id, status, observacao)
    values (
      v_id,
      v_status,
      coalesce(v_observacao, case when p_id is null then 'Sugestão registrada no sistema.' else null end)
    );
  end if;

  return v_id;
end;
$$;

create or replace function public.delete_sugestao_melhoria(
  p_password text,
  p_id bigint
)
returns boolean
language plpgsql
security definer
set search_path = ''
as $$
declare
  v_afetados integer;
begin
  if not public.admin_password_ok(p_password) then
    raise exception 'Senha administrativa inválida';
  end if;

  delete from public.sugestoes_melhoria where id = p_id;
  get diagnostics v_afetados = row_count;
  return v_afetados > 0;
end;
$$;

revoke execute on function public.save_auditor_cadastrado(text, bigint, text, bigint) from public;
revoke execute on function public.delete_auditor_cadastrado(text, bigint) from public;
revoke execute on function public.save_sugestao_melhoria(
  text, bigint, text, text, text[], bigint[], text, text
) from public;
revoke execute on function public.delete_sugestao_melhoria(text, bigint) from public;

grant execute on function public.save_auditor_cadastrado(text, bigint, text, bigint)
  to anon, authenticated, service_role;
grant execute on function public.delete_auditor_cadastrado(text, bigint)
  to anon, authenticated, service_role;
grant execute on function public.save_sugestao_melhoria(
  text, bigint, text, text, text[], bigint[], text, text
) to anon, authenticated, service_role;
grant execute on function public.delete_sugestao_melhoria(text, bigint)
  to anon, authenticated, service_role;

notify pgrst, 'reload schema';
