create table public.liderancas (
  id bigint generated by default as identity primary key,
  nome text not null,
  cargo text not null,
  setor text not null default 'corporativo',
  superior_id bigint references public.liderancas(id) on delete set null,
  ativo boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint liderancas_nome_not_blank check (btrim(nome) <> ''),
  constraint liderancas_setor_not_blank check (btrim(setor) <> ''),
  constraint liderancas_cargo_check check (cargo in ('Supervisor', 'Gestor', 'Gerente', 'Diretor')),
  constraint liderancas_superior_diferente check (superior_id is null or superior_id <> id)
);

create unique index liderancas_nome_cargo_setor_ativo_uidx
  on public.liderancas (lower(btrim(nome)), cargo, lower(btrim(setor)))
  where ativo;

create index liderancas_superior_ativo_idx
  on public.liderancas (superior_id)
  where ativo;

create index liderancas_cargo_setor_ativo_idx
  on public.liderancas (cargo, setor, nome)
  where ativo;

alter table public.liderancas enable row level security;

create policy "Lideranças ativas são públicas para leitura"
  on public.liderancas
  for select
  to anon, authenticated
  using (ativo);

revoke all on table public.liderancas from anon, authenticated;
grant select on table public.liderancas to anon, authenticated;
grant all on table public.liderancas to service_role;

create view public.liderancas_publicas
with (security_invoker = true)
as
select
  lider.id,
  lider.nome,
  lider.cargo,
  lider.setor,
  lider.superior_id,
  superior.nome as superior_nome,
  superior.cargo as superior_cargo,
  case lider.cargo
    when 'Supervisor' then 1
    when 'Gestor' then 2
    when 'Gerente' then 3
    when 'Diretor' then 4
  end as nivel,
  lider.created_at,
  lider.updated_at
from public.liderancas lider
left join public.liderancas superior
  on superior.id = lider.superior_id
 and superior.ativo
where lider.ativo;

revoke all on table public.liderancas_publicas from public;
grant select on table public.liderancas_publicas to anon, authenticated, service_role;

create or replace function public.save_lideranca(
  p_password text,
  p_id bigint,
  p_nome text,
  p_cargo text,
  p_setor text,
  p_superior_id bigint
)
returns bigint
language plpgsql
security definer
set search_path = public, extensions
as $$
declare
  v_id bigint;
  v_nome text := btrim(coalesce(p_nome, ''));
  v_cargo text := btrim(coalesce(p_cargo, ''));
  v_setor text := btrim(coalesce(p_setor, ''));
  v_cargo_superior text;
  v_cargo_esperado text;
begin
  if not public.admin_password_ok(p_password) then
    raise exception 'Senha administrativa inválida';
  end if;

  if v_nome = '' or v_setor = '' or v_cargo not in ('Supervisor', 'Gestor', 'Gerente', 'Diretor') then
    raise exception 'Preencha nome, cargo e área/setor da liderança';
  end if;

  v_cargo_esperado := case v_cargo
    when 'Supervisor' then 'Gestor'
    when 'Gestor' then 'Gerente'
    when 'Gerente' then 'Diretor'
    else null
  end;

  if v_cargo = 'Diretor' and p_superior_id is not null then
    raise exception 'Diretor é o nível mais alto e não pode possuir superior direto';
  end if;

  if p_superior_id is not null then
    if p_id is not null and p_superior_id = p_id then
      raise exception 'Uma pessoa não pode ser superior de si mesma';
    end if;

    select cargo
    into v_cargo_superior
    from public.liderancas
    where id = p_superior_id
      and ativo;

    if v_cargo_superior is null then
      raise exception 'Superior direto não encontrado';
    end if;

    if v_cargo_superior <> v_cargo_esperado then
      raise exception 'O superior direto de % deve possuir o cargo %', v_cargo, v_cargo_esperado;
    end if;
  end if;

  if p_id is not null and exists (
    select 1
    from public.liderancas subordinado
    where subordinado.superior_id = p_id
      and subordinado.ativo
      and subordinado.cargo <> case v_cargo
        when 'Gestor' then 'Supervisor'
        when 'Gerente' then 'Gestor'
        when 'Diretor' then 'Gerente'
        else ''
      end
  ) then
    raise exception 'O novo cargo não é compatível com os subordinados diretos já vinculados';
  end if;

  if p_id is null then
    insert into public.liderancas (nome, cargo, setor, superior_id)
    values (v_nome, v_cargo, v_setor, p_superior_id)
    returning id into v_id;
  else
    update public.liderancas
    set nome = v_nome,
        cargo = v_cargo,
        setor = v_setor,
        superior_id = p_superior_id,
        ativo = true,
        updated_at = now()
    where id = p_id
    returning id into v_id;

    if v_id is null then
      raise exception 'Cadastro de liderança não encontrado';
    end if;
  end if;

  return v_id;
end;
$$;

revoke execute on function public.save_lideranca(text, bigint, text, text, text, bigint) from public;
grant execute on function public.save_lideranca(text, bigint, text, text, text, bigint)
  to anon, authenticated, service_role;

create or replace function public.delete_lideranca(
  p_password text,
  p_id bigint
)
returns boolean
language plpgsql
security definer
set search_path = public, extensions
as $$
declare
  v_afetados integer;
begin
  if not public.admin_password_ok(p_password) then
    raise exception 'Senha administrativa inválida';
  end if;

  update public.liderancas
  set superior_id = null,
      updated_at = now()
  where superior_id = p_id
    and ativo;

  update public.liderancas
  set ativo = false,
      superior_id = null,
      updated_at = now()
  where id = p_id
    and ativo;

  get diagnostics v_afetados = row_count;
  return v_afetados > 0;
end;
$$;

revoke execute on function public.delete_lideranca(text, bigint) from public;
grant execute on function public.delete_lideranca(text, bigint)
  to anon, authenticated, service_role;
