create table public.colaboradores_operacionais (
  id bigint generated by default as identity primary key,
  nome text not null,
  cargo text not null,
  setor text not null,
  ativo boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint colaboradores_operacionais_nome_not_blank check (btrim(nome) <> ''),
  constraint colaboradores_operacionais_cargo_not_blank check (btrim(cargo) <> ''),
  constraint colaboradores_operacionais_setor_not_blank check (btrim(setor) <> '')
);

create unique index colaboradores_operacionais_nome_setor_ativo_uidx
  on public.colaboradores_operacionais (lower(btrim(nome)), lower(btrim(setor)))
  where ativo;

create index colaboradores_operacionais_setor_nome_ativo_idx
  on public.colaboradores_operacionais (setor, nome)
  where ativo;

alter table public.colaboradores_operacionais enable row level security;

create policy "Colaboradores operacionais ativos são públicos para leitura"
  on public.colaboradores_operacionais
  for select
  to anon, authenticated
  using (ativo);

revoke all on table public.colaboradores_operacionais from anon, authenticated;
grant select on table public.colaboradores_operacionais to anon, authenticated;
grant all on table public.colaboradores_operacionais to service_role;

create view public.colaboradores_operacionais_publicos
with (security_invoker = true)
as
select id, nome, cargo, setor, created_at, updated_at
from public.colaboradores_operacionais
where ativo;

revoke all on table public.colaboradores_operacionais_publicos from public;
grant select on table public.colaboradores_operacionais_publicos
  to anon, authenticated, service_role;

create or replace function public.save_colaborador_operacional(
  p_password text,
  p_id bigint,
  p_nome text,
  p_cargo text,
  p_setor text
)
returns bigint
language plpgsql
security definer
set search_path = ''
as $$
declare
  v_id bigint;
  v_nome text := btrim(coalesce(p_nome, ''));
  v_cargo text := btrim(coalesce(p_cargo, ''));
  v_setor text := btrim(coalesce(p_setor, ''));
  v_nome_anterior text;
  v_setor_anterior text;
begin
  if not public.admin_password_ok(p_password) then
    raise exception 'Senha administrativa inválida';
  end if;

  if v_nome = '' or v_cargo = '' or v_setor = '' then
    raise exception 'Preencha nome, cargo e setor do colaborador';
  end if;

  if p_id is null then
    insert into public.colaboradores_operacionais (nome, cargo, setor)
    values (v_nome, v_cargo, v_setor)
    returning id into v_id;
  else
    select nome, setor
    into v_nome_anterior, v_setor_anterior
    from public.colaboradores_operacionais
    where id = p_id
      and ativo;

    if v_nome_anterior is null then
      raise exception 'Cadastro de colaborador não encontrado';
    end if;

    update public.colaboradores_operacionais
    set nome = v_nome,
        cargo = v_cargo,
        setor = v_setor,
        updated_at = now()
    where id = p_id
    returning id into v_id;

    if lower(btrim(v_setor_anterior)) = lower(v_setor) then
      update public.subordinacoes
      set subordinado = v_nome,
          cargo = v_cargo,
          updated_at = now()
      where ativo
        and lower(btrim(setor)) = lower(btrim(v_setor_anterior))
        and lower(btrim(subordinado)) = lower(btrim(v_nome_anterior));
    else
      update public.subordinacoes
      set ativo = false,
          updated_at = now()
      where ativo
        and lower(btrim(setor)) = lower(btrim(v_setor_anterior))
        and lower(btrim(subordinado)) = lower(btrim(v_nome_anterior));
    end if;
  end if;

  return v_id;
end;
$$;

revoke execute on function public.save_colaborador_operacional(text, bigint, text, text, text) from public;
grant execute on function public.save_colaborador_operacional(text, bigint, text, text, text)
  to anon, authenticated, service_role;

create or replace function public.delete_colaborador_operacional(
  p_password text,
  p_id bigint
)
returns boolean
language plpgsql
security definer
set search_path = ''
as $$
declare
  v_nome text;
  v_setor text;
  v_afetados integer;
begin
  if not public.admin_password_ok(p_password) then
    raise exception 'Senha administrativa inválida';
  end if;

  select nome, setor
  into v_nome, v_setor
  from public.colaboradores_operacionais
  where id = p_id
    and ativo;

  update public.colaboradores_operacionais
  set ativo = false,
      updated_at = now()
  where id = p_id
    and ativo;

  get diagnostics v_afetados = row_count;

  if v_afetados > 0 then
    update public.subordinacoes
    set ativo = false,
        updated_at = now()
    where ativo
      and lower(btrim(setor)) = lower(btrim(v_setor))
      and lower(btrim(subordinado)) = lower(btrim(v_nome));
  end if;

  return v_afetados > 0;
end;
$$;

revoke execute on function public.delete_colaborador_operacional(text, bigint) from public;
grant execute on function public.delete_colaborador_operacional(text, bigint)
  to anon, authenticated, service_role;

-- O formulário de subordinação também passa a cadastrar o colaborador e só aceita
-- supervisores existentes no cadastro formal de liderança do mesmo setor.
create or replace function public.save_subordinacao(
  p_password text,
  p_id bigint,
  p_setor text,
  p_supervisor text,
  p_subordinado text,
  p_cargo text
)
returns bigint
language plpgsql
security definer
set search_path = ''
as $$
declare
  v_id bigint;
  v_setor text := btrim(coalesce(p_setor, ''));
  v_supervisor text := btrim(coalesce(p_supervisor, ''));
  v_subordinado text := btrim(coalesce(p_subordinado, ''));
  v_cargo text := btrim(coalesce(p_cargo, ''));
begin
  if not public.admin_password_ok(p_password) then
    raise exception 'Senha inválida';
  end if;
  if v_setor = '' or v_supervisor = '' or v_subordinado = '' or v_cargo = '' then
    raise exception 'Preencha setor, supervisor, subordinado e cargo';
  end if;
  if lower(v_supervisor) = lower(v_subordinado) then
    raise exception 'Supervisor e subordinado devem ser pessoas diferentes';
  end if;
  if not exists (
    select 1
    from public.liderancas lider
    where lider.ativo
      and lider.cargo = 'Supervisor'
      and lower(btrim(lider.setor)) = lower(v_setor)
      and lower(btrim(lider.nome)) = lower(v_supervisor)
  ) then
    raise exception 'Cadastre o supervisor na liderança e no mesmo setor antes de criar o vínculo';
  end if;

  if not exists (
    select 1
    from public.colaboradores_operacionais colaborador
    where colaborador.ativo
      and lower(btrim(colaborador.setor)) = lower(v_setor)
      and lower(btrim(colaborador.nome)) = lower(v_subordinado)
  ) then
    raise exception 'Cadastre primeiro o colaborador operacional neste setor';
  end if;

  update public.colaboradores_operacionais
  set cargo = v_cargo,
      updated_at = now()
  where ativo
    and lower(btrim(setor)) = lower(v_setor)
    and lower(btrim(nome)) = lower(v_subordinado);

  update public.subordinacoes
  set ativo = false, updated_at = now()
  where ativo
    and lower(btrim(setor)) = lower(v_setor)
    and lower(btrim(subordinado)) = lower(v_subordinado)
    and (p_id is null or id <> p_id);

  if p_id is null then
    insert into public.subordinacoes (setor, supervisor, subordinado, cargo)
    values (v_setor, v_supervisor, v_subordinado, v_cargo)
    returning id into v_id;
  else
    update public.subordinacoes
    set setor = v_setor,
        supervisor = v_supervisor,
        subordinado = v_subordinado,
        cargo = v_cargo,
        ativo = true,
        updated_at = now()
    where id = p_id
    returning id into v_id;

    if v_id is null then
      raise exception 'Vínculo de subordinação não encontrado';
    end if;
  end if;

  return v_id;
end;
$$;

revoke execute on function public.save_subordinacao(text, bigint, text, text, text, text) from public;
grant execute on function public.save_subordinacao(text, bigint, text, text, text, text)
  to anon, authenticated, service_role;

-- Nenhuma nova auditoria é aceita sem um cadastro ativo compatível com o setor.
create or replace function public.save_auditoria_contextual(
  p_password text,
  p_audit_id bigint,
  p_type text,
  p_team text,
  p_audit_date date,
  p_cargo text,
  p_score numeric,
  p_total_ok integer,
  p_total_no integer,
  p_report jsonb,
  p_supervisor_name text,
  p_audited_role text
)
returns boolean
language plpgsql
security definer
set search_path = ''
as $$
declare
  v_role text := coalesce(nullif(btrim(p_audited_role), ''), 'supervisor');
  v_supervisor text := nullif(btrim(p_supervisor_name), '');
  v_setor text := lower(btrim(coalesce(p_type, '')));
  v_nome text := btrim(coalesce(p_team, ''));
begin
  if not public.admin_password_ok(p_password) then
    raise exception 'Senha inválida';
  end if;
  if v_role not in ('supervisor', 'subordinado') then
    raise exception 'Tipo de auditado inválido';
  end if;
  if v_setor = '' or v_nome = '' then
    raise exception 'Setor e colaborador são obrigatórios';
  end if;

  if v_role = 'supervisor' then
    if not exists (
      select 1
      from public.liderancas lider
      where lider.ativo
        and lider.cargo = 'Supervisor'
        and lower(btrim(lider.setor)) = v_setor
        and lower(btrim(lider.nome)) = lower(v_nome)
    ) then
      raise exception 'Supervisor não cadastrado na liderança deste setor';
    end if;
    v_supervisor := v_nome;
  else
    if not exists (
      select 1
      from public.colaboradores_operacionais colaborador
      where colaborador.ativo
        and lower(btrim(colaborador.setor)) = v_setor
        and lower(btrim(colaborador.nome)) = lower(v_nome)
    ) then
      raise exception 'Colaborador não cadastrado no nível operacional deste setor';
    end if;

    if v_supervisor is not null and not exists (
      select 1
      from public.subordinacoes vinculo
      where vinculo.ativo
        and lower(btrim(vinculo.setor)) = v_setor
        and lower(btrim(vinculo.subordinado)) = lower(v_nome)
        and lower(btrim(vinculo.supervisor)) = lower(v_supervisor)
    ) then
      raise exception 'Vínculo ativo entre colaborador, supervisor e setor não encontrado';
    end if;
  end if;

  insert into public.auditorias (
    audit_id, type, team, audit_date, cargo, score, total_ok, total_no, report,
    supervisor_name, audited_role
  ) values (
    p_audit_id, p_type, v_nome, p_audit_date, p_cargo, p_score, p_total_ok, p_total_no,
    coalesce(p_report, '{}'::jsonb), v_supervisor, v_role
  )
  on conflict (audit_id) do update set
    type = excluded.type,
    team = excluded.team,
    audit_date = excluded.audit_date,
    cargo = excluded.cargo,
    score = excluded.score,
    total_ok = excluded.total_ok,
    total_no = excluded.total_no,
    report = excluded.report,
    supervisor_name = excluded.supervisor_name,
    audited_role = excluded.audited_role;

  return true;
end;
$$;

revoke execute on function public.save_auditoria_contextual(
  text, bigint, text, text, date, text, numeric, integer, integer, jsonb, text, text
) from public;
grant execute on function public.save_auditoria_contextual(
  text, bigint, text, text, date, text, numeric, integer, integer, jsonb, text, text
) to anon, authenticated, service_role;

-- Migra os operadores e supervisores já conhecidos, preservando os vínculos atuais.
insert into public.colaboradores_operacionais (nome, cargo, setor)
select distinct s.subordinado, s.cargo, s.setor
from public.subordinacoes s
where s.ativo
  and not exists (
    select 1
    from public.colaboradores_operacionais c
    where c.ativo
      and lower(btrim(c.nome)) = lower(btrim(s.subordinado))
      and lower(btrim(c.setor)) = lower(btrim(s.setor))
  );

insert into public.liderancas (nome, cargo, setor, superior_id)
select distinct
  s.supervisor,
  'Supervisor',
  s.setor,
  (
    select gestor.id
    from public.liderancas gestor
    where gestor.ativo
      and gestor.cargo = 'Gestor'
      and lower(btrim(gestor.setor)) = lower(btrim(s.setor))
    order by gestor.id
    limit 1
  )
from public.subordinacoes s
where s.ativo
  and not exists (
    select 1
    from public.liderancas lider
    where lider.ativo
      and lider.cargo = 'Supervisor'
      and lower(btrim(lider.nome)) = lower(btrim(s.supervisor))
      and lower(btrim(lider.setor)) = lower(btrim(s.setor))
  );

insert into public.liderancas (nome, cargo, setor, superior_id)
select 'Lazinho', 'Supervisor', 'prensa', null
where not exists (
  select 1
  from public.liderancas lider
  where lider.ativo
    and lider.cargo = 'Supervisor'
    and lower(btrim(lider.nome)) = 'lazinho'
    and lower(btrim(lider.setor)) = 'prensa'
);

update public.liderancas
set ativo = false,
    superior_id = null,
    updated_at = now()
where ativo
  and lower(btrim(nome)) = 'daiane';

insert into public.colaboradores_operacionais (nome, cargo, setor)
select 'Daiane', 'Analista de Laboratório', 'laboratorio'
where not exists (
  select 1
  from public.colaboradores_operacionais c
  where c.ativo
    and lower(btrim(c.nome)) = 'daiane'
    and lower(btrim(c.setor)) = 'laboratorio'
);

update public.auditorias
set audited_role = 'subordinado',
    supervisor_name = null,
    report = coalesce(report, '{}'::jsonb) || '{"auditedRole":"subordinado","supervisorName":null}'::jsonb
where lower(btrim(team)) = 'daiane'
  and lower(btrim(type)) = 'laboratorio';

-- Subdivisões da diretoria e gerências informadas pela operação.
update public.liderancas
set setor = 'diretoria_industrial',
    superior_id = null,
    updated_at = now()
where ativo
  and cargo = 'Diretor'
  and lower(btrim(nome)) = 'wagner';

insert into public.liderancas (nome, cargo, setor, superior_id)
select 'Wagner', 'Diretor', 'diretoria_industrial', null
where not exists (
  select 1 from public.liderancas
  where ativo and cargo = 'Diretor' and lower(btrim(nome)) = 'wagner'
);

insert into public.liderancas (nome, cargo, setor, superior_id)
select 'Júlio', 'Diretor', 'diretoria_financeira', null
where not exists (
  select 1 from public.liderancas
  where ativo and cargo = 'Diretor' and lower(btrim(nome)) = lower('Júlio')
);

insert into public.liderancas (nome, cargo, setor, superior_id)
select cadastro.nome, 'Gerente', cadastro.setor, diretor.id
from (
  values
    ('João Paulo'::text, 'engenharia'::text),
    ('José Roberto Madalena'::text, 'qualidade_laboratorio'::text),
    ('Japa'::text, 'producao'::text),
    ('Fernando'::text, 'prensa'::text)
) as cadastro(nome, setor)
cross join lateral (
  select id
  from public.liderancas
  where ativo
    and cargo = 'Diretor'
    and lower(btrim(nome)) = 'wagner'
  order by id
  limit 1
) diretor
where not exists (
  select 1
  from public.liderancas existente
  where existente.ativo
    and existente.cargo = 'Gerente'
    and lower(btrim(existente.nome)) = lower(btrim(cadastro.nome))
);

update public.liderancas gerente
set setor = cadastro.setor,
    superior_id = diretor.id,
    updated_at = now()
from (
  values
    ('João Paulo'::text, 'engenharia'::text),
    ('José Roberto Madalena'::text, 'qualidade_laboratorio'::text),
    ('Japa'::text, 'producao'::text),
    ('Fernando'::text, 'prensa'::text)
) as cadastro(nome, setor)
cross join lateral (
  select id
  from public.liderancas
  where ativo
    and cargo = 'Diretor'
    and lower(btrim(nome)) = 'wagner'
  order by id
  limit 1
) diretor
where gerente.ativo
  and gerente.cargo = 'Gerente'
  and lower(btrim(gerente.nome)) = lower(btrim(cadastro.nome));

update public.liderancas gestor
set superior_id = gerente.id,
    updated_at = now()
from public.liderancas gerente
where gestor.ativo
  and gestor.cargo = 'Gestor'
  and lower(btrim(gestor.setor)) in ('forno', 'laminacao')
  and gerente.ativo
  and gerente.cargo = 'Gerente'
  and lower(btrim(gerente.nome)) = 'japa';
